module.exports = {
    FB_PAGE_TOKEN: process.FB_PAGE_TOKEN,
    FB_VERIFY_TOKEN: process.FB_VERIFY_TOKEN,
    FB_APP_SECRET: process.FB_APP_SECRET,
    SERVER_URL: process.SERVER_URL,
    GOOGLE_PROJECT_ID: process.GOOGLE_PROJECT_ID,
    DF_LANGUAGE_CODE: process.DF_LANGUAGE_CODE,
    GOOGLE_CLIENT_EMAIL: process.GOOGLE_CLIENT_EMAIL,
    GOOGLE_PRIVATE_KEY: process.GOOGLE_PRIVATE_KEY
};